### PR TITLE
Update metadata 

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Update metadata and added files to .gitignore
Will be updating screenshots

### CODE REVIEW

**Comment by quozl** [comment]
tags say it is a Game, but it isn't a game.

repository has unnecessary www prefix.

Because of https://github.com/sugarlabs/laybrinth-activity/issues/1 my preference is to hold off on merging this one until the disparate and confusing source code repositories have been resolved by an activity maintainer.

**Comment by vipulgupta2048** [comment]
@quozl  I was thinking of adding `Tools` to our category list. Some things in the computer help out in productivity and work. This category can be it. This could include Develop, Sugar Commander etc. What do you think.

**Comment by vipulgupta2048** [comment]
Roger that on the holding, it's a mess.

**Comment by quozl** [comment]
Reviewed to 20dfab3.

**Comment by quozl** [comment]
Reviewed to 511591b.  You changed labyrinthactivity.py license to "lesser"?  Now the license isn't consistent.  Not sure what you meant to do.

**Comment by vipulgupta2048** [comment]
@quozl Changes made as requested, ready to go.

**Comment by quozl** [comment]
Doesn't look like anyone is interested in #1 yet, merging anyway.

**Comment by vipulgupta2048** [comment]
@quozl I will give it a swing and open a PR this weekend if no one takes it up.

**Pull request merged**
