### PR TITLE
Port to Python3 [GCI]

### PR DESCRIPTION
**Pull request by srevinsaju**
* [x] Port to Python3
* [x] Fix other Logical Errors
* [x] Make the activity runnable
* [x] Test all the functions of Labyrinth Activity
* [ ] Fix test not displaying (or is it on purpose?)
* [x] Test on Sugar ISO
* [x] Pep8 and Flake8

What Labyrinth was on Master Branch
* Broken files (Files missing, import errors on python2)
* A wrong RGB code of (Red, Green, Red). [b47d71e5cb966e978e63fe4f90d1635cd40e5720 ]
* Tarball files were not working
* Text displayed only when user types, once its closed, it is blank rectangle
* Saving files had bugs

### CODE REVIEW

**Comment by srevinsaju** [comment]
@quozl I fixed most of errors, but idk if the text is hidden on purpose. It didn't work in python2. Kindly review

Also, you might like to cherry pick https://github.com/sugarlabs/labyrinth-activity/pull/8/commits/b47d71e5cb966e978e63fe4f90d1635cd40e5720 to python2 branch

**Comment by quozl** [comment]
Thanks.  The text is intended to remain visible.

**Comment by quozl** [comment]
Cherry-picked b47d71e.

**Comment by quozl** [comment]
Thanks!

I've merged two of the disconnected repositories mentioned in https://github.com/sugarlabs/labyrinth-activity/issues/1; the first is https://github.com/ndefilippis/Laybrinth-Sugar which is a fork of the original repository, and the second is the commits in this repository which started with the Port to GTK 3.  You can see the result in the [gitorious](https://github.com/sugarlabs/labyrinth-activity/commits/gitorious) branch, where @cristian99garcia's commits are applied (and rehashed) after the latest commits from git.sugarlabs.org.  This repository should have been a clone of git.sugarlabs.org.  From memory it wasn't @cristian99garcia's fault; the mentors gave bad advice during GCI 2015.

I've tested https://github.com/sugarlabs/labyrinth-activity/commit/0acc5757f8d64f4d719e3adcc144c2f1036d5d55 before the Port to GTK 3, on Ubuntu 16.04 Xenial, and confirmed that text does stay in the boxes.

Screenshot_ubuntu-xenial_2020-01-21_17:49:06

So the loss of text is a regression in the Port to GTK 3, which has not yet been released.

I suggest iterating through the changes in https://github.com/sugarlabs/labyrinth-activity/commit/1d5903aaf67fb202cc39c18d94a869d081dfe392 and following commits on the _gitorious_ branch to try to find where the regression is introduced.

**Comment by srevinsaju** [comment]
Closing this as I wasn't able to make any much good progress. :(

**Pull request closed without merging**
